server:
  port: 8080
  servlet:
    context-path: /crm

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm?useUnicode=true$characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: guo027437

  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gxx.crm.vo;com.gxx.crm.query;com.gxx.crm.dto
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com:
      gxx:
        crm:
          dao: debug